name: trotter_flutter
description: A travel guide app.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.8+86

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  lazy_loading_list: ^1.0.0+1
  auto_size_text: ^2.1.0
  autocomplete_textfield: ^1.7.3
  datetime_picker_formfield: ^1.0.0
  flutter_widgets: ^0.1.7+1
  flutter_form_builder: ^3.7.3
  webview_flutter: ^0.3.19+5
  rating_bar: ^0.2.0
  url_launcher: ^5.1.3
  showcaseview: ^0.1.5
  date_range_picker: ^1.0.6
  lazy_load_scrollview: ^1.0.1
  duration: ^2.0.8
  firebase_dynamic_links: ^0.5.0+8
  flutter_store: ^1.0.0+4
  firebase_messaging: ^6.0.9
  share: ^0.6.3+1
  http: 0.12.0+2
  dio: ^3.0.8
  flutter_svg: ^0.17.1
  shared_preferences: ^0.5.6+1
  sliding_up_panel: ^1.0.0
  flutter_swiper: ^1.1.6
  transformer_page_view: ^0.1.6
  google_maps_flutter: ^0.5.21+11
  shimmer: ^0.0.6
  flare_flutter: ^1.6.2
  flare_loading: ^2.1.0
  intl: ^0.16.0
  html_unescape: ^1.0.1+2
  html: ^0.14.0+3
  flutter_typeahead: ^1.8.0
  queries: ^0.1.12
  recase: ^2.0.0+1
  flutter_page_indicator: ^0.0.3
  bubble_bottom_bar: ^1.2.0
  flutter_vector_icons: ^0.2.1
  transparent_image: ^0.1.0
  firebase_auth: ^0.15.4
  google_sign_in: ^4.1.1
  timezone: ^0.5.5
  badges: ^1.1.0
  flutter_advanced_networkimage: ^0.6.4
  timeago: ^2.0.19
  notification_permissions: ^0.4.3
  location: ^2.3.5
  permission_handler: ^4.0.0
  awesome_loader: ^0.0.3
  country_code_picker: ^1.1.7
  geolocator: ^5.1.3
  flutter_launcher_icons: "^0.7.0"
  device_info: ^0.4.1+3
  event_bus: ^1.1.0
  strings: ^0.1.0
  overlay_support: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/home_bg.jpeg
    - images/comment-icon.svg
    - images/header.png
    - images/headerPreview.jpeg
    - images/trips.jpg
    - images/logo.png
    - images/day-empty.jpg
    - images/cannot-view.jpg
    - images/trips-empty.jpg
    - images/notification-empty.jpg
    - images/error-icon.jpg
    - images/error-icon.png
    - images/email-icon.jpg
    - images/email-icon.png
    - images/email-icon2.png
    - images/trips2.jpg
    - images/trips-login.png
    - images/trips-login.jpg
    - images/server-error-icon.png
    - images/header.svg
    - images/google-logo.svg
    - images/directions-icon.svg
    - images/google-logo.png
    - images/logo_nw.png
    - images/trotter-logo.svg
    - images/refresh_icon.svg
    - images/edit-icon.svg
    - images/delete-icon.svg
    - images/logo_nw_black.png
    - images/vaccines.png
    - images/risk.png
    - images/placeholder.jpg
    - images/placeholder.png
    - images/search2.jpg
    - images/see.jpg
    - images/nightlife.jpg
    - images/shopping.jpg
    - images/food.jpg
    - images/search-icon.svg
    - images/setting-icon.svg
    - images/back-icon.svg
    - images/add-location.svg
    - images/add-icon.svg
    - images/add-location-bold.svg
    - images/trip-icon.svg
    - images/notification.svg
    - images/itinerary-icon.svg
    - images/trips-icon.svg
    - images/explore-icon.svg
    - images/forward.svg
    - images/avatar-icon.svg
    - images/place-icon.svg
    - images/see-icon.svg
    - images/nightlife-icon.svg
    - images/eat-icon.svg
    - images/shopping-icon.svg
    - images/reminder-icon.svg
    - images/mark-all.svg
    - images/hat.svg
    - images/hat_2.svg
    - images/sun-umbrella.svg
    - images/jacket.svg
    - images/sweater.svg
    - images/flip-flops.svg
    - images/swimming-trunks.svg
    - images/place-icon.png
    - images/reminder-icon.png
    - images/A.png
    - images/B.png
    - images/C.png
    - images/D.png
    - images/E.png
    - images/F.png
    - images/G.png
    - images/H.png
    - images/I.png
    - images/J.png
    - images/K.png
    - images/L.png
    - images/M.png
    - images/N.png
    - images/trips-empty.png
    - packages/timezone/data/2019b.tzf
    - assets/Map.flr
    - assets/Plane.flr
    - assets/globe.flr
    - assets/loading_earth.flr
    - assets/foddie-maker-loading.flr
    - assets/airlines.json
    - assets/airports_stations.json
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
